### ISSUE TITLE
Wazuh Plugin - OwlH UI integration with Wazuh Plugin

### ISSUE THREAD

**Issue by 72nomada** [OwlH-net/OwlH-UIREACT#16]
- [x] get architecture 
- [x] create NIDS frontal page /wazuh#nids/
- [x] create owlh nodes table listing current master nodes
    - [x] define a table with main owlh node fields
    - [x] integrate owlh master API call under wazuh plugin server configuration.
    - [x] get node list and update table
- [ ] clean code and libraries structure definition 
- [ ] make main NIDS page accessing a summary and options like nodes, groups, open-rules, master, config
- [ ] where should we include a call to the main NIDS page? 
- [ ] add a NIDS tag to wazuh nodes that are running as OwlH Nodes
